import { mamaris, santiago, buenosAires, bruge, andermatt, stPetersburg, mykonos, albufeira, jasper, orlando } from '@/public';

export const exploreTheWorldData = [
  {
    id: 0,
    title: 'Comfort Space',
    location: 'Mamaris, Turkey',
    rooms: 33,
    costPerNight: 250,
    fiveStarRating: 4.5,
    totalReviews: 86,
    image: mamaris,
    distanceToTownCenter: '0.5 km',
  },
  {
    id: 1,
    title: 'La Casa Barco Hostel',
    location: 'Santiago, Chile',
    rooms: 166,
    costPerNight: 150,
    fiveStarRating: 4.6,
    totalReviews: 190,
    image: santiago,
    distanceToTownCenter: '8.5 km',
  },
  {
    id: 2,
    title: 'Hotel Villa del Parque',
    location: 'Buenos Aires, Argentina',
    rooms: 99,
    costPerNight: 143,
    fiveStarRating: 4.3,
    totalReviews: 111,
    image: buenosAires,
    distanceToTownCenter: '1.5 km',
  },
  {
    id: 3,
    title: 'Hotel Fevery',
    location: 'Bruge, Belgium',
    rooms: 10,
    costPerNight: 200,
    fiveStarRating: 4.9,
    totalReviews: 609,
    image: bruge,
    distanceToTownCenter: '1.2 km',
  },
  {
    id: 4,
    title: 'The Chedi Andermatt',
    location: 'Andermatt, Switzerland',
    rooms: 250,
    costPerNight: 533,
    fiveStarRating: 5,
    totalReviews: 786,
    image: andermatt,
    distanceToTownCenter: '0.5 km',
  },
  {
    id: 5,
    title: 'Hotel Lion Palace St. Petersburg',
    location: 'St. Petersburg, Russia',
    rooms: 350,
    costPerNight: 300,
    fiveStarRating: 4.8,
    totalReviews: 1427,
    image: stPetersburg,
    distanceToTownCenter: '0.3 km',
  },
  {
    id: 6,
    title: 'Anax Resort & Spa',
    location: 'Mykonos, Greece',
    rooms: 100,
    costPerNight: 270,
    fiveStarRating: 4.9,
    totalReviews: 220,
    image: mykonos,
    distanceToTownCenter: '1.75 km',
  },
  {
    id: 7,
    title: 'Hotel Sol E Mar',
    location: 'Albufeira, Portugal',
    rooms: 220,
    costPerNight: 97,
    fiveStarRating: 4.2,
    totalReviews: 698,
    image: albufeira,
    distanceToTownCenter: '1.80 km',
  },
  {
    id: 8,
    title: 'Chateau Jasper',
    location: 'Jasper, Canada',
    rooms: 80,
    costPerNight: 124,
    fiveStarRating: 4.2,
    totalReviews: 834,
    image: jasper,
    distanceToTownCenter: '3.2 km',
  },
  {
    id: 9,
    title: 'Liki Tiki Village',
    location: 'Orlando, USA',
    rooms: 150,
    costPerNight: 118,
    fiveStarRating: 4.1,
    totalReviews: 7545,
    image: orlando,
    distanceToTownCenter: '8.5 km',
  },
];

