import { mamaris, santiago, buenosAires, bruge, andermatt, stPetersburg, mykonos, albufeira, jasper, orlando } from '@/public';
import { title } from 'process';

export const hotelListingData = [
  {
    id: 0,
    title: 'Comfort Space',
    location: 'Mamaris, Turkey',
    rooms: 33,
    costPerNight: 250,
    fiveStarRating: 4.5,
    totalReviews: 86,
    image: mamaris,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Free Wifi',
        image: '/icons/Wifi.svg'
      },
      {
        title: 'Free Parking',
        image: '/icons/Parking.svg'
      },
      {
        title: 'Pool',
        image: '/icons/Swimming.svg'
      }, 
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
    ],  
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 1,
    title: 'La Casa Barco Hostel',
    location: 'Santiago, Chile',
    rooms: 166,
    costPerNight: 150,
    fiveStarRating: 4.6,
    totalReviews: 190,
    image: santiago,
    distanceToTownCenter: '8.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Free Wifi',
        image: '/icons/Wifi.svg',
      },
      {
        title: 'Free Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Gym',
        image: '/icons/Gym.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
    ],
    specialOffer: false,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 2,
    title: 'Hotel Villa del Parque',
    location: 'Buenos Aires, Argentina',
    rooms: 99,
    costPerNight: 143,
    fiveStarRating: 4.3,
    totalReviews: 111,
    image: buenosAires,
    distanceToTownCenter: '1.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Resort',
    facilities: [
      {
        title: 'Free Wifi',
        image: '/icons/Wifi.svg',
      },
      {
        title: 'Free Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Golf Course',
        image: '/icons/Golf.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      }, 
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 3,
    title: 'Hotel De Orangerie',
    location: 'Brugge, Belgium',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: bruge,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Room Service', 
        image: '/icons/RoomService.svg',
      },
      {
        title: 'Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Pool',
        image: '/icons/Swimming.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 4,
    title: 'Hotel Alpenhof',
    location: 'Andermatt, Switzerland',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: andermatt,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Parking', 
        image: '/icons/Parking.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
      {
        title: 'Gym',
        image: '/icons/Gym.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 5,
    title: 'Hotel Astoria',
    location: 'St. Petersburg, Russia',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: stPetersburg,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
      {
        title: 'Gym',
        image: '/icons/Gym.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 6,
    title: 'Hotel Mykonos',
    location: 'Mykonos, Greece',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: mykonos,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
      {
        title: 'Gym',
        image: '/icons/Gym.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 7,
    title: 'Hotel Albufeira',
    location: 'Albufeira, Portugal',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: albufeira,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Air Conditioning',
        image: '/icons/AirConditioning.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 8,
    title: 'Hotel Jasper',
    location: 'Jasper, Canada',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: jasper,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Wifi',
        image: '/icons/Wifi.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
      {
        title: 'Gym',
        image: '/icons/Gym.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 9,
    title: 'Hotel Alpenhof',
    location: 'Andermatt, Switzerland',
    rooms: 50,
    costPerNight: 200,
    fiveStarRating: 4.8,
    totalReviews: 78,
    image: andermatt,
    distanceToTownCenter: '0.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Hotel',
    facilities: [
      {
        title: 'Wifi',
        image: '/icons/Wifi.svg',
      },
      {
        title: 'Restaurant',
        image: '/icons/Restaurant.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
      {
        title: 'Gym',
        image: '/icons/Gym.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
  {
    id: 10,
    title: 'Liki Tiki Village',
    location: 'Orlando, USA',
    rooms: 150,
    costPerNight: 118,
    fiveStarRating: 4.1,
    totalReviews: 7545,
    image: orlando,
    distanceToTownCenter: '8.5 km',
    depatureLocation: 'New York, NY',
    checkInDate: '2020-12-01',
    checkOutDate: '2020-12-05',
    propertyType: 'Resort',
    facilities: [
      {
        title: 'Wifi',
        image: '/icons/Wifi.svg',
      },
      {
        title: 'Parking',
        image: '/icons/Parking.svg',
      },
      {
        title: 'Golf Course',
        image: '/icons/Golf.svg',
      },
      {
        title: 'Bar',
        image: '/icons/Bar.svg',
      },
      {
        title: 'Spa',
        image: '/icons/Spa.svg',
      },
    ],
    specialOffer: true,
    website: '',
    safetyMeasures: true,
  },
];


